export enum ChatEvents {
    START_SESSION = 'START_SESSION',
    SESSION_START = 'SESSION_START',
    
    SEND_MESSAGE = 'SEND_MESSAGE',
    NEW_MESSAGE = 'NEW_MESSAGE',

    CLOSE_SESSION = 'CLOSE_SESSION',
    SESSION_CLOSE = 'SESSION_CLOSE', 

    SESSION_ERROR = 'SESSION_ERROR'
}